# Generated by Django 5.2.8 on 2025-12-02 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(default='CS', on_delete=django.db.models.deletion.CASCADE, to='practice.department'),
        ),
    ]
