# Generated by Django 5.2.8 on 2025-12-04 04:19

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_alter_student_department'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='student',
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
    ]
