# Generated by Django 5.2.8 on 2025-12-05 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0005_person_child_teacher'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='student_table',
        ),
    ]
